#!/usr/bin/env ruby
# I'm using this file because at the time of writing, the Rails 3 exec file
# doesn't allow for running older versions side by side

require 'rubygems'

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

if version =~ /^3|[^.]3/
  # Rails 3...
  gem 'railties', version
  load Gem.bin_path('railties', 'rails', version)
else
  # ... pre Rails 3
  gem 'rails', version
  load Gem.bin_path('rails', 'rails', version)
end